---
# - name: Ensure dependencies are installed (Yum).
#   ansible.builtin.yum:
#     name:
#       - flatpak
#     state: present

- name: Ensure flatpak is installed (Yum).
  ansible.builtin.yum:
    name:
      - flatpak
    state: present
